# Generated by Django 5.2.11 on 2026-02-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Profile picture (auto-compressed to 400x400 JPEG)",
                null=True,
                upload_to="avatars/",
            ),
        ),
    ]
