# Generated by Django 5.2.11 on 2026-02-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_tools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogdraft",
            name="ai_model_used",
            field=models.CharField(
                blank=True,
                default="claude",
                help_text="AI model used: claude, openai, auto",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="blogdraft",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                help_text="Featured image for the blog post (auto-compressed to max 1200x800)",
                null=True,
                upload_to="drafts/images/",
            ),
        ),
        migrations.AddField(
            model_name="ideagenerationrequest",
            name="ai_model_used",
            field=models.CharField(
                blank=True,
                default="claude",
                help_text="AI model used: claude, openai, auto",
                max_length=30,
            ),
        ),
    ]
