# Generated by Django 5.2.11 on 2026-02-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_tools", "0002_blogdraft_ai_model_used_blogdraft_featured_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogdraft",
            name="outline",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="SEO blog outline generated before full blog",
            ),
        ),
        migrations.AddField(
            model_name="blogdraft",
            name="seo_keywords",
            field=models.JSONField(
                blank=True, default=list, help_text="SEO focus keywords"
            ),
        ),
        migrations.AddField(
            model_name="blogdraft",
            name="summary",
            field=models.JSONField(
                blank=True, default=list, help_text="Key takeaway bullet points"
            ),
        ),
    ]
